services:
  heatpump:
    image: ghcr.io/essagl/tuya-spring-boot-aircal-heat-pump-adapter/heatpump:latest
    container_name: heatpump
    ports:
      - "8080:8080"
    volumes:
      - heatpump_data:/app
    networks:
      - influxdb-telegraf_default

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=password
    command: influxd -config /etc/influxdb/influxdb.conf
    networks:
      - influxdb-telegraf_default

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOSTNAME=telegraf
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DATABASE=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_PASSWORD=password
    networks:
      - influxdb-telegraf_default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://grafana/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - influxdb-telegraf_default

networks:
  influxdb-telegraf_default:
    driver: bridge

volumes:
  heatpump_data:
    driver: local
  influxdb_data:
    driver: local
  grafana_storage:
    driver: local

